[2023-01-26T14:02:29.867+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spotify_dag.crawl_s3 scheduled__2023-01-26T12:00:00+00:00 [queued]>
[2023-01-26T14:02:29.873+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spotify_dag.crawl_s3 scheduled__2023-01-26T12:00:00+00:00 [queued]>
[2023-01-26T14:02:29.873+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T14:02:29.873+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-01-26T14:02:29.873+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T14:02:29.894+0000] {taskinstance.py:1383} INFO - Executing <Task(GlueCrawlerOperator): crawl_s3> on 2023-01-26 12:00:00+00:00
[2023-01-26T14:02:29.898+0000] {standard_task_runner.py:55} INFO - Started process 1998 to run task
[2023-01-26T14:02:29.901+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'spotify_dag', 'crawl_s3', 'scheduled__2023-01-26T12:00:00+00:00', '--job-id', '384', '--raw', '--subdir', 'DAGS_FOLDER/airflow_dags.py', '--cfg-path', '/tmp/tmpcujp1wp4']
[2023-01-26T14:02:29.903+0000] {standard_task_runner.py:83} INFO - Job 384: Subtask crawl_s3
[2023-01-26T14:02:29.944+0000] {task_command.py:376} INFO - Running <TaskInstance: spotify_dag.crawl_s3 scheduled__2023-01-26T12:00:00+00:00 [running]> on host ip-172-31-26-59.ap-northeast-2.compute.internal
[2023-01-26T14:02:30.004+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nywkim@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=spotify_dag
AIRFLOW_CTX_TASK_ID=crawl_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-01-26T12:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-26T12:00:00+00:00
[2023-01-26T14:02:30.005+0000] {glue_crawler.py:55} INFO - Checking if crawler already exists: spotify-crawl
[2023-01-26T14:02:30.011+0000] {base.py:71} INFO - Using connection ID 'aws_default' for task execution.
[2023-01-26T14:02:30.012+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2023-01-26T14:02:30.715+0000] {base.py:71} INFO - Using connection ID 'aws_default' for task execution.
[2023-01-26T14:02:30.716+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2023-01-26T14:02:31.003+0000] {glue_crawler.py:82} INFO - Triggering AWS Glue Crawler
[2023-01-26T14:02:31.004+0000] {glue_crawler.py:151} INFO - Starting crawler spotify-crawl
[2023-01-26T14:02:31.112+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/amazon/aws/operators/glue_crawler.py", line 83, in execute
    self.hook.start_crawler(crawler_name)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/amazon/aws/hooks/glue_crawler.py", line 152, in start_crawler
    return self.glue_client.start_crawler(Name=crawler_name)
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.CrawlerRunningException: An error occurred (CrawlerRunningException) when calling the StartCrawler operation: Crawler with name spotify-crawl has already started
[2023-01-26T14:02:31.117+0000] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_dag, task_id=crawl_s3, execution_date=20230126T120000, start_date=20230126T140229, end_date=20230126T140231
[2023-01-26T14:02:31.127+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 384 for task crawl_s3 (An error occurred (CrawlerRunningException) when calling the StartCrawler operation: Crawler with name spotify-crawl has already started; 1998)
[2023-01-26T14:02:31.156+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-26T14:02:31.171+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
