[2023-01-24T18:32:58.083+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spotify_dag.crawl_s3 manual__2023-01-24T18:30:03.247767+00:00 [queued]>
[2023-01-24T18:32:58.089+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spotify_dag.crawl_s3 manual__2023-01-24T18:30:03.247767+00:00 [queued]>
[2023-01-24T18:32:58.090+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-24T18:32:58.090+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-01-24T18:32:58.090+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-24T18:32:58.103+0000] {taskinstance.py:1383} INFO - Executing <Task(GlueCrawlerOperator): crawl_s3> on 2023-01-24 18:30:03.247767+00:00
[2023-01-24T18:32:58.106+0000] {standard_task_runner.py:55} INFO - Started process 5567 to run task
[2023-01-24T18:32:58.110+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'spotify_dag', 'crawl_s3', 'manual__2023-01-24T18:30:03.247767+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/airflow_dags.py', '--cfg-path', '/tmp/tmpyh2mgrk0']
[2023-01-24T18:32:58.111+0000] {standard_task_runner.py:83} INFO - Job 283: Subtask crawl_s3
[2023-01-24T18:32:58.151+0000] {task_command.py:376} INFO - Running <TaskInstance: spotify_dag.crawl_s3 manual__2023-01-24T18:30:03.247767+00:00 [running]> on host ip-172-31-26-59.ap-northeast-2.compute.internal
[2023-01-24T18:32:58.199+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nywkim@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=spotify_dag
AIRFLOW_CTX_TASK_ID=crawl_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-01-24T18:30:03.247767+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-24T18:30:03.247767+00:00
[2023-01-24T18:32:58.200+0000] {glue_crawler.py:55} INFO - Checking if crawler already exists: spotify-crawl
[2023-01-24T18:32:58.204+0000] {base.py:71} INFO - Using connection ID 'aws_default' for task execution.
[2023-01-24T18:32:58.205+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2023-01-24T18:32:58.797+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/amazon/aws/operators/glue_crawler.py", line 77, in execute
    if self.hook.has_crawler(crawler_name):
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/amazon/aws/hooks/glue_crawler.py", line 58, in has_crawler
    self.get_crawler(crawler_name)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/amazon/aws/hooks/glue_crawler.py", line 70, in get_crawler
    return self.glue_client.get_crawler(Name=crawler_name)["Crawler"]
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the GetCrawler operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
[2023-01-24T18:32:58.800+0000] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_dag, task_id=crawl_s3, execution_date=20230124T183003, start_date=20230124T183258, end_date=20230124T183258
[2023-01-24T18:32:58.811+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 283 for task crawl_s3 (An error occurred (InvalidSignatureException) when calling the GetCrawler operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.; 5567)
[2023-01-24T18:32:58.842+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-24T18:32:58.858+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
